---@diagnostic disable: lowercase-global
------------------------------------------------------
--                                                  --
--                 Tattoo Options                   --
--                                                  --
------------------------------------------------------
tCC:AddDummy(0,5)
CCBody = tCC:AddCollapsingHeader("Tattoo")
tCC:AddSeparatorText("")

tattooAtlasHeader = CCBody:AddCollapsingHeader("Tattoo Selection")
tattooAtlasTable = tattooAtlasHeader:AddTable("", 10)
tattooAtlasRow1 = tattooAtlasTable:AddRow()
tattooAtlasButton0 = tattooAtlasRow1:AddCell():AddButton("0")
tattooAtlasButton1 = tattooAtlasRow1:AddCell():AddButton("1")
tattooAtlasButton2 = tattooAtlasRow1:AddCell():AddButton("2")
tattooAtlasButton3 = tattooAtlasRow1:AddCell():AddButton("3")
tattooAtlasButton4 = tattooAtlasRow1:AddCell():AddButton("4")
tattooAtlasButton5 = tattooAtlasRow1:AddCell():AddButton("5")
tattooAtlasButton6 = tattooAtlasRow1:AddCell():AddButton("6")
tattooAtlasButton7 = tattooAtlasRow1:AddCell():AddButton("7")
tattooAtlasButton8 = tattooAtlasRow1:AddCell():AddButton("8")
tattooAtlasButton9 = tattooAtlasRow1:AddCell():AddButton("9")
tattooAtlasRow2 = tattooAtlasTable:AddRow()
tattooAtlasButton10 = tattooAtlasRow2:AddCell():AddButton("10")
tattooAtlasButton11 = tattooAtlasRow2:AddCell():AddButton("11")
tattooAtlasButton12 = tattooAtlasRow2:AddCell():AddButton("12")
tattooAtlasButton13 = tattooAtlasRow2:AddCell():AddButton("13")
tattooAtlasButton14 = tattooAtlasRow2:AddCell():AddButton("14")
tattooAtlasButton15 = tattooAtlasRow2:AddCell():AddButton("15")
tattooAtlasButton16 = tattooAtlasRow2:AddCell():AddButton("16")
tattooAtlasButton17 = tattooAtlasRow2:AddCell():AddButton("17")
tattooAtlasButton18 = tattooAtlasRow2:AddCell():AddButton("18")
tattooAtlasButton19 = tattooAtlasRow2:AddCell():AddButton("19")
CCBody:AddDummy(0,5)
CCBody:AddDummy(0,5)
tattooSliderHeader = CCBody:AddCollapsingHeader("Tattoo Sliders")
tattooSliderTable = tattooSliderHeader:AddTable("", 1)
tattooSliderRow1 = tattooSliderTable:AddRow()
tattooSliderRow2 = tattooSliderTable:AddRow()
metallicSelector = tattooSliderRow1:AddCell():AddSliderInt("Metallicness", 0, 0, 100)
intensitySelector = tattooSliderRow2:AddCell():AddSliderInt("Intensity", 0, 0, 100)
CCBody:AddDummy(0,5)
CCBody:AddDummy(0,5)
tattooColorHeader = CCBody:AddCollapsingHeader("Tattoo Color")
tattooColorTable = tattooColorHeader:AddTable("", 5)
tattooColorRow1 = tattooColorTable:AddRow()
tattooColorRow2 = tattooColorTable:AddRow()
tattooColorButton1 = tattooColorRow1:AddCell():AddButton("Protector")
tattooColorButton2 = tattooColorRow1:AddCell():AddButton("Scourge")
tattooColorButton3 = tattooColorRow1:AddCell():AddButton("Fallen")
tattooColorButton4 = tattooColorRow1:AddCell():AddButton("Harbinger")
tattooColorButton5 = tattooColorRow1:AddCell():AddButton("Pink")
tattooColorButton6 = tattooColorRow2:AddCell():AddButton("Purple")
tattooColorButton7 = tattooColorRow2:AddCell():AddButton("White")
tattooColorButton8 = tattooColorRow2:AddCell():AddButton("Black")
tattooColorButton9 = tattooColorRow2:AddCell():AddButton("Silver")
tattooColorButton10 = tattooColorRow2:AddCell():AddButton("Gold")
CCBody:AddDummy(0,5)
CCBody:AddDummy(0,5)
tattooSaveHeader = CCBody:AddCollapsingHeader("Finish")
tattooSaveTable = tattooSaveHeader:AddTable("", 10)
tattooSaveRow1 = tattooSaveTable:AddRow()
tattooSaveButton1 = tattooSaveRow1:AddCell():AddButton("Save")
tattooSaveButton1 = tattooSaveRow1:AddCell():AddButton("Exit")



tattooAtlasButton0.OnClick = function()
    print("Clicked 0")
    Ext.Net.PostMessageToServer("changeTattoo0", "OnClick")
end

tattooAtlasButton1.OnClick = function()
    print("Clicked 1")
    Ext.Net.PostMessageToServer("changeTattoo1", "OnClick")
end